Update Build-KernelSU-Next.yml

diff --git a/.github/workflows/Build-KernelSU-Next.yml b/.github/workflows/Build-KernelSU-Next.yml
--- a/.github/workflows/Build-KernelSU-Next.yml
+++ b/.github/workflows/Build-KernelSU-Next.yml
@@ -138,16 +138,19 @@ jobs:
          rm -rf ./AnyKernel3/.git
          cp kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image ./AnyKernel3/
 
-      - name: Download latest susfs4ksu module
+      - name: Download Latest SUSFS Module
         env:
-          GH_TOKEN: ${{ github.token }}
+          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # 引用自定义 Secret
         run: |
           LATEST_URL=$(curl -sSLH "Authorization: Bearer $GH_TOKEN" \
             https://api.github.com/repos/sidex15/susfs4ksu-module/releases/latest \
             | jq -r '.assets[] | select(.name | test("ksu_module_susfs_1.5.2\\+.*\\.zip")) | .browser_download_url')
           curl -LO "$LATEST_URL"
-          echo "Downloaded file: $(ls ksu_module_susfs_1.5.2+*.zip)"         
-          mv ksu_module_susfs_1.5.2+.zip ./AnyKernel3/         
+          if [ ! -f *.zip ]; then
+            echo "Error: File not downloaded!"
+            exit 1
+          fi
+          mv ksu_module_susfs_1.5.2+.zip ./AnyKernel3/
 
       - name: Upload AnyKernel3
         uses: actions/upload-artifact@v4
